{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bluelink-token.fullname" . }}
  labels:
    {{- include "bluelink-token.labels" . | nindent 4 }}
type: Opaque
stringData:
  BLUELINK_USERNAME: {{ .Values.secrets.BLUELINK_USERNAME | quote }}
  BLUELINK_PASSWORD: {{ .Values.secrets.BLUELINK_PASSWORD | quote }}
  EVCC_PASSWORD: {{ .Values.secrets.EVCC_PASSWORD | quote }}
{{- end }}
